export const analyticsEvents = {
	pageView: '$pageview',
	viewMapHome: 'view_map_home',
	navigationTabSelected: 'navigation_tab_selected',
	selectZone: 'select_zone',
	selectCategory: 'select_category',
	searchOpened: 'search_opened',
	searchPlace: 'search_place',
	searchResultSelected: 'search_result_selected',
	clickPlaceMarker: 'click_place_marker',
	openPlaceSheet: 'open_place_sheet',
	clickPlaceDetail: 'click_place_detail',
	selectBuilding: 'select_building',
	clickShuttleMarker: 'click_shuttle_marker',
	selectShuttleRoute: 'select_shuttle_route',
	openCafeteria: 'open_cafeteria',
	selectCafeteria: 'select_cafeteria',
	selectMealDate: 'select_meal_date',
	menuReactionChanged: 'menu_reaction_changed',
	openToday: 'open_today',
	selectTodayTab: 'select_today_tab',
	viewEventDetail: 'view_event_detail',
	selectEvent: 'select_event',
	openMeetup: 'open_meetup',
	createMeetupStart: 'create_meetup_start',
	createMeetupComplete: 'create_meetup_complete',
	loginSuccess: 'login_success',
	onboardingComplete: 'onboarding_complete'
} as const;

export type AnalyticsEventName = (typeof analyticsEvents)[keyof typeof analyticsEvents];
